# Generated by Django 5.2.17 on 2026-09-06 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('category', models.CharField(choices=[('lich_nghi', 'Lịch nghỉ'), ('su_kien', 'Sự kiện'), ('vang_mat', 'Vắng mặt'), ('hoc_tap', 'Học tập'), ('khac', 'Khác')], default='khac', max_length=20, verbose_name='Phân loại')),
                ('published_at', models.DateTimeField(blank=True, help_text='Bỏ trống = còn là nháp.', null=True, verbose_name='Thời điểm đăng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenancy.house')),
                ('student', models.ForeignKey(blank=True, help_text='Bỏ trống = thông báo cho toàn bộ cơ sở.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people.student')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt đọc thông báo',
                'verbose_name_plural': 'Lượt đọc thông báo',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['house', 'published_at'], name='notificatio_house_i_f9bdd2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', 'published_at'], name='notificatio_student_97b429_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='uniq_notification_read'),
        ),
    ]
