# Generated by Django 5.2.17 on 2026-09-11 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Đã gửi'), ('failed', 'Gửi lỗi')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký email',
                'verbose_name_plural': 'Nhật ký email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_email', 'created_at'], name='notificatio_to_emai_3588e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('login', 'Đăng nhập'), ('change_email', 'Đổi email'), ('reset_password', 'Đặt lại mật khẩu')], max_length=20)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mã OTP',
                'verbose_name_plural': 'Mã OTP',
                'indexes': [models.Index(fields=['user', 'purpose', 'expires_at'], name='notificatio_user_id_cee267_idx')],
            },
        ),
    ]
