# Generated by Django 5.2.17 on 2026-09-06 05:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khoản thu')),
                ('category', models.CharField(choices=[('tuition', 'Học phí'), ('meal', 'Tiền ăn'), ('transport', 'Phí xe'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Nhóm')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền mặc định')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='tenancy.house')),
            ],
            options={
                'verbose_name': 'Khoản thu',
                'verbose_name_plural': 'Khoản thu',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên gói')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('due_day_of_month', models.PositiveSmallIntegerField(default=5, help_text='1-31. Nếu tháng không có ngày này thì lùi về ngày cuối tháng.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hạn đóng (ngày trong tháng)')),
                ('billing_timing', models.CharField(choices=[('prepaid', 'Thu trước'), ('postpaid', 'Thu sau')], default='prepaid', max_length=10, verbose_name='Thời điểm thu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_packages', to='tenancy.house')),
            ],
            options={
                'verbose_name': 'Gói phí',
                'verbose_name_plural': 'Gói phí',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Bỏ trống để dùng default_amount của khoản thu.', max_digits=12, null=True, verbose_name='Số tiền')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_links', to='billing.feeitem')),
                ('fee_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.feepackage')),
            ],
            options={
                'verbose_name': 'Khoản thu trong gói',
                'verbose_name_plural': 'Khoản thu trong gói',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Dùng ngày đầu tháng của kỳ, vd 2026-09-01.', verbose_name='Kỳ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Dương = cộng thêm, âm = trừ bớt.', max_digits=12, verbose_name='Điều chỉnh')),
                ('adjustment_note', models.CharField(blank=True, max_length=500, verbose_name='Lý do điều chỉnh')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('issued', 'Đã phát hành'), ('partially_paid', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('void', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('due_date', models.DateField(verbose_name='Hạn thanh toán')),
                ('qr_reference_code', models.CharField(help_text='Chuỗi xuất hiện trong nội dung chuyển khoản, dùng để tự khớp giao dịch.', max_length=40, unique=True, verbose_name='Mã tham chiếu QR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenancy.house')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='people.student')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'ordering': ['-period', 'student__person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_item_name_snapshot', models.CharField(help_text='Chốt tại thời điểm phát hành để hóa đơn cũ không đổi khi FeeItem đổi tên.', max_length=255, verbose_name='Tên khoản thu (snapshot)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='billing.feeitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Dòng hóa đơn',
                'verbose_name_plural': 'Dòng hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền hoàn')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Lý do')),
                ('refunded_at', models.DateTimeField(verbose_name='Thời điểm hoàn')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.invoice')),
                ('refunded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoàn tiền',
                'verbose_name_plural': 'Hoàn tiền',
                'ordering': ['-refunded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên giảm trừ')),
                ('discount_type', models.CharField(choices=[('percentage', 'Theo phần trăm'), ('fixed_amount', 'Số tiền cố định')], default='percentage', max_length=20, verbose_name='Kiểu')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị')),
                ('effective_from', models.DateField(verbose_name='Áp dụng từ')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('fee_item', models.ForeignKey(blank=True, help_text='Bỏ trống = áp dụng trên toàn hóa đơn.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='billing.feeitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='people.student')),
            ],
            options={
                'verbose_name': 'Giảm trừ',
                'verbose_name_plural': 'Giảm trừ',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Áp dụng từ')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến')),
                ('fee_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.feepackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_packages', to='people.student')),
            ],
            options={
                'verbose_name': 'Gói phí của học sinh',
                'verbose_name_plural': 'Gói phí của học sinh',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='feepackage',
            constraint=models.CheckConstraint(condition=models.Q(('due_day_of_month__gte', 1), ('due_day_of_month__lte', 31)), name='fee_package_due_day_in_range'),
        ),
        migrations.AddConstraint(
            model_name='feepackageitem',
            constraint=models.UniqueConstraint(fields=('fee_package', 'fee_item'), name='uniq_package_item'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['house', 'period'], name='billing_inv_house_i_5c47bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='uniq_invoice_student_period'),
        ),
        migrations.AddIndex(
            model_name='studentfeepackage',
            index=models.Index(fields=['student', 'effective_from'], name='billing_stu_student_33b11a_idx'),
        ),
    ]
