# Generated by Django 5.2.17 on 2026-09-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_feeitem_created_at_feeitem_updated_at_and_more'),
        ('payments', '0002_bankaccount_created_at_bankaccount_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancel_reason',
            field=models.CharField(blank=True, help_text='Ghi khi status chuyển sang VOID — qua nút hủy tay hoặc hoàn tiền có hủy nghĩa vụ.', max_length=500, verbose_name='Lý do hủy'),
        ),
        migrations.AddField(
            model_name='refund',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt'), ('credit', 'Giữ làm credit')], default='bank_transfer', max_length=20, verbose_name='Phương thức hoàn'),
        ),
        migrations.AddField(
            model_name='refund',
            name='needs_adjustment_invoice',
            field=models.BooleanField(default=False, help_text='Đặt True khi hóa đơn gốc đã có hóa đơn điện tử — xử lý riêng, không chặn luồng hoàn tiền nội bộ. Hệ thống hiện chưa theo dõi hóa đơn điện tử nên cờ này luôn False cho tới khi có tính năng đó.', verbose_name='Cần lập hóa đơn điều chỉnh'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Payment gốc liên quan, nếu xác định được — không bắt buộc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.payment'),
        ),
    ]
