# Generated by Django 5.2.4 on 2026-09-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_cancel_reason_refund_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('issued', 'Đã phát hành'), ('partially_paid', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('fully_refunded', 'Đã hoàn đủ'), ('void', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
