# Generated by Django 5.2.17 on 2026-09-06 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, verbose_name='Nơi sinh')),
                ('nationality', models.CharField(blank=True, default='Việt Nam', max_length=100, verbose_name='Quốc tịch')),
                ('ethnicity', models.CharField(blank=True, max_length=100, verbose_name='Dân tộc')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='Số CCCD/CMND')),
                ('id_issued_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('id_issued_place', models.CharField(blank=True, max_length=255, verbose_name='Nơi cấp')),
                ('permanent_address', models.CharField(blank=True, max_length=500, verbose_name='Hộ khẩu thường trú')),
                ('current_address', models.CharField(blank=True, max_length=500, verbose_name='Chỗ ở hiện tại')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhân thân',
                'verbose_name_plural': 'Nhân thân',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('mother', 'Mẹ'), ('father', 'Bố'), ('grandparent', 'Ông/Bà'), ('sibling', 'Anh/Chị/Em'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Quan hệ')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Liên hệ chính')),
            ],
            options={
                'verbose_name': 'Phụ huynh của học sinh',
                'verbose_name_plural': 'Phụ huynh của học sinh',
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Giáo viên chính')),
                ('assigned_from', models.DateField(verbose_name='Từ ngày')),
                ('assigned_until', models.DateField(blank=True, null=True, verbose_name='Đến ngày')),
            ],
            options={
                'verbose_name': 'Phân công giảng dạy',
                'verbose_name_plural': 'Phân công giảng dạy',
                'ordering': ['-assigned_from'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guardian', serialize=False, to='people.person')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Nghề nghiệp')),
            ],
            options={
                'verbose_name': 'Phụ huynh',
                'verbose_name_plural': 'Phụ huynh',
                'ordering': ['person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to='people.person')),
                ('class_grade', models.CharField(blank=True, max_length=50, verbose_name='Lớp')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('paused', 'Tạm nghỉ'), ('graduated', 'Đã tốt nghiệp'), ('withdrawn', 'Đã nghỉ')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('enrolled_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhập học')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
                'ordering': ['person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to='people.person')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'ordering': ['person__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name'], name='people_pers_full_na_9fcb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone'], name='people_pers_phone_b55729_idx'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='people.guardian'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='people.student'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='people.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenancy.house', verbose_name='Cơ sở'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='people.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='tenancy.house', verbose_name='Cơ sở'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='uniq_student_guardian'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['house', 'status'], name='people_stud_house_i_a94c09_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['student', 'assigned_from'], name='people_teac_student_bf1d9a_idx'),
        ),
    ]
