# Generated by Django 5.2.17 on 2026-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_guardian_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiền hoàn giữ lại (không chuyển khoản/tiền mặt) — trừ dần vào hóa đơn kỳ sau.', max_digits=12, verbose_name='Số dư credit'),
        ),
    ]
