# Generated by Django 5.2.17 on 2026-09-06 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=20, verbose_name='Mã ngân hàng')),
                ('account_number_last4', models.CharField(help_text='Chỉ lưu 4 số cuối — không lưu số tài khoản đầy đủ.', max_length=4, verbose_name='4 số cuối tài khoản')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Chủ tài khoản')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='tenancy.house')),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
            },
        ),
        migrations.CreateModel(
            name='BankIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sepay', 'SePay')], default='sepay', max_length=20)),
                ('sepay_account_id', models.CharField(blank=True, max_length=100, verbose_name='SePay account id')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='API key (mã hóa)')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook secret')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_integration', to='tenancy.house')),
            ],
            options={
                'verbose_name': 'Kết nối ngân hàng',
                'verbose_name_plural': 'Kết nối ngân hàng',
            },
        ),
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('transfer_content', models.CharField(blank=True, max_length=500, verbose_name='Nội dung chuyển khoản')),
                ('transaction_time', models.DateTimeField(verbose_name='Thời điểm giao dịch')),
                ('status', models.CharField(choices=[('unmatched', 'Chưa khớp'), ('partially_matched', 'Khớp một phần'), ('matched', 'Đã khớp'), ('ignored', 'Bỏ qua')], default='unmatched', max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(default='webhook_sepay', max_length=50, verbose_name='Nguồn')),
                ('provider_transaction_id', models.CharField(help_text='Khóa chống ghi trùng khi webhook gửi lại.', max_length=100, unique=True, verbose_name='Mã giao dịch bên cung cấp')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload gốc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='tenancy.house')),
            ],
            options={
                'verbose_name': 'Giao dịch tiền vào',
                'verbose_name_plural': 'Giao dịch tiền vào',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền phân bổ')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt'), ('other', 'Khác')], default='bank_transfer', max_length=20, verbose_name='Hình thức')),
                ('matched_by', models.CharField(choices=[('auto', 'Tự động'), ('manual', 'Thủ công')], default='manual', max_length=10, verbose_name='Cách khớp')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('recorded_by_user', models.ForeignKey(blank=True, help_text='Bắt buộc trên thực tế với thu tiền mặt — để truy trách nhiệm.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Bỏ trống nếu thu tiền mặt.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.incomingtransaction')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incomingtransaction',
            index=models.Index(fields=['house', 'status', 'transaction_time'], name='payments_in_house_i_fc3f05_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'created_at'], name='payments_pa_invoice_4000b7_idx'),
        ),
    ]
