# Generated by Django 5.2.17 on 2026-09-10 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bankaccount_created_at_bankaccount_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number_last4',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number_encrypted',
            field=models.TextField(default='', verbose_name='Số tài khoản (mã hóa)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(choices=[('970425', 'ABBANK'), ('970416', 'ACB'), ('970405', 'Agribank'), ('970409', 'BacABank'), ('970438', 'BaoVietBank'), ('970418', 'BIDV'), ('546034', 'CAKE'), ('422589', 'CIMB'), ('970446', 'COOPBANK'), ('970431', 'Eximbank'), ('970437', 'HDBank'), ('668888', 'KBank'), ('970452', 'KienLongBank'), ('970449', 'LPBank'), ('970422', 'MBBank'), ('970414', 'MBV'), ('971025', 'MoMo'), ('970426', 'MSB'), ('970428', 'NamABank'), ('970419', 'NCB'), ('970448', 'OCB'), ('970430', 'PGBank'), ('970412', 'PVcomBank'), ('971133', 'PVcomBank Pay'), ('970403', 'Sacombank'), ('970400', 'SaigonBank'), ('970429', 'SCB'), ('970440', 'SeABank'), ('970443', 'SHB'), ('970424', 'ShinhanBank'), ('970407', 'Techcombank'), ('963388', 'Timo'), ('970423', 'TPBank'), ('546035', 'Ubank'), ('970441', 'VIB'), ('970427', 'VietABank'), ('970433', 'VietBank'), ('970454', 'VietCapitalBank'), ('970436', 'Vietcombank'), ('970415', 'VietinBank'), ('970432', 'VPBank'), ('970457', 'Woori')], max_length=20, verbose_name='Ngân hàng'),
        ),
        migrations.CreateModel(
            name='BankAccountRevealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveal_logs', to='payments.bankaccount')),
                ('revealed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_reveals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lượt xem số tài khoản',
                'verbose_name_plural': 'Lượt xem số tài khoản',
                'ordering': ['-created_at'],
            },
        ),
    ]
