# Generated by Django 5.2.17 on 2026-09-11 04:00

import django.db.models.deletion
from django.db import migrations, models


def set_existing_as_primary(apps, schema_editor):
    # Trước migration này mỗi house có tối đa 1 BankAccount (OneToOne) — đánh
    # dấu primary để VietQR không im lặng ngừng hoạt động sau khi nâng cấp.
    BankAccount = apps.get_model('payments', 'BankAccount')
    BankAccount.objects.update(is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_bankaccount_account_number_last4_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['house_id', '-is_primary', '-created_at'], 'verbose_name': 'Tài khoản ngân hàng', 'verbose_name_plural': 'Tài khoản ngân hàng'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Tài khoản chính'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenancy.house'),
        ),
        migrations.RunPython(set_existing_as_primary, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('house',), name='unique_primary_bank_account_per_house'),
        ),
    ]
