# Generated by Django 5.2.17 on 2026-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cơ sở')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('inbound_email_slug', models.SlugField(help_text='Dùng cho địa chỉ nhận mail/webhook riêng của cơ sở.', max_length=63, unique=True, verbose_name='Slug email nhận thư')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cơ sở',
                'verbose_name_plural': 'Cơ sở',
                'ordering': ['name'],
            },
        ),
    ]
